apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: milankwiatkowski/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:$(POSTGRES_PASSWORD)@db:5432/postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
